#!/bin/bash
# =============================================================================
# PathView Pro - Secure Environment Setup
# =============================================================================
# This script generates secure random passwords and creates the .env file
# Run this ONCE during initial deployment setup
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
ENV_TEMPLATE="$PROJECT_ROOT/config/env.example"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}PathView Pro - Secure Environment Setup${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}WARNING: .env file already exists at $ENV_FILE${NC}"
    read -p "Do you want to overwrite it? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
    echo ""
fi

# Function to generate secure random password
generate_password() {
    local length=${1:-32}
    # Use /dev/urandom for secure random generation
    # Filter to alphanumeric + some special chars, avoid problematic chars for configs
    LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*_+-=' < /dev/urandom | head -c "$length"
}

# Generate passwords
echo "Generating secure passwords..."
POSTGRES_PASSWORD=$(generate_password 32)
ORTHANC_PASSWORD=$(generate_password 32)
SESSION_SECRET=$(generate_password 64)

echo -e "${GREEN}✓${NC} Generated POSTGRES_PASSWORD"
echo -e "${GREEN}✓${NC} Generated ORTHANC_PASSWORD"
echo -e "${GREEN}✓${NC} Generated SESSION_SECRET"
echo ""

# Prompt for configuration
echo "Please provide the following configuration values:"
echo "(Press Enter to accept the default value shown in brackets)"
echo ""

read -p "Auth0 Domain [dev-jkm887wawwxknno6.us.auth0.com]: " AUTH0_DOMAIN
AUTH0_DOMAIN=${AUTH0_DOMAIN:-"dev-jkm887wawwxknno6.us.auth0.com"}

read -p "Auth0 Audience [https://pathviewpro.com/api]: " AUTH0_AUDIENCE
AUTH0_AUDIENCE=${AUTH0_AUDIENCE:-"https://pathviewpro.com/api"}

read -p "Auth0 Client ID [oORvvnuGhZ9365zxTrZNY33jnoSm9wr3]: " AUTH0_CLIENT_ID
AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID:-"oORvvnuGhZ9365zxTrZNY33jnoSm9wr3"}

read -p "Public URL [https://pathviewpro.com]: " PUBLIC_URL
PUBLIC_URL=${PUBLIC_URL:-"https://pathviewpro.com"}

read -p "SSL Domain [pathviewpro.com]: " SSL_DOMAIN
SSL_DOMAIN=${SSL_DOMAIN:-"pathviewpro.com"}

read -p "SSL Email [admin@pathviewpro.com]: " SSL_EMAIL
SSL_EMAIL=${SSL_EMAIL:-"admin@pathviewpro.com"}

read -p "Enable TLS/HTTPS? (y/N): " ENABLE_TLS
if [ "$ENABLE_TLS" == "y" ] || [ "$ENABLE_TLS" == "Y" ]; then
    ENABLE_TLS="true"
else
    ENABLE_TLS="false"
fi

echo ""
echo "Creating .env file..."

# Create .env file
cat > "$ENV_FILE" << EOF
# =============================================================================
# PathView Pro - Environment Configuration
# =============================================================================
# Generated by setup-secure-env.sh on $(date)
# WARNING: This file contains secrets - NEVER commit to version control!
# =============================================================================

# -----------------------------------------------------------------------------
# Database Credentials
# -----------------------------------------------------------------------------
POSTGRES_DB=orthanc
POSTGRES_USER=orthanc
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# -----------------------------------------------------------------------------
# Orthanc DICOM Server Credentials
# -----------------------------------------------------------------------------
ORTHANC_USERNAME=admin
ORTHANC_PASSWORD=$ORTHANC_PASSWORD

# -----------------------------------------------------------------------------
# Auth0 Configuration
# -----------------------------------------------------------------------------
AUTH0_DOMAIN=$AUTH0_DOMAIN
AUTH0_AUDIENCE=$AUTH0_AUDIENCE
AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID

# -----------------------------------------------------------------------------
# Application Settings
# -----------------------------------------------------------------------------
PUBLIC_URL=$PUBLIC_URL
MAX_UPLOAD_SIZE_GB=20

# -----------------------------------------------------------------------------
# TLS/SSL Configuration
# -----------------------------------------------------------------------------
ENABLE_TLS=$ENABLE_TLS
SSL_DOMAIN=$SSL_DOMAIN
SSL_EMAIL=$SSL_EMAIL

# -----------------------------------------------------------------------------
# Security Settings
# -----------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS=$PUBLIC_URL
SESSION_SECRET=$SESSION_SECRET

# -----------------------------------------------------------------------------
# Redis Configuration
# -----------------------------------------------------------------------------
REDIS_URL=redis://redis:6379
EOF

# Set restrictive permissions on .env file
chmod 600 "$ENV_FILE"

echo -e "${GREEN}✓${NC} Created .env file at $ENV_FILE"
echo -e "${GREEN}✓${NC} Set file permissions to 600 (owner read/write only)"
echo ""

# Generate base64 encoded auth for Nginx
ORTHANC_AUTH_BASE64=$(echo -n "admin:$ORTHANC_PASSWORD" | base64)
echo -e "${YELLOW}IMPORTANT: Update viewer/Dockerfile with this auth string:${NC}"
echo -e "  Authorization: Basic ${ORTHANC_AUTH_BASE64}"
echo ""

echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "Next steps:"
echo "1. Review the generated .env file"
echo "2. Update Nginx config with the new credentials"
echo "3. Rebuild containers: docker compose build"
echo "4. Restart services: docker compose up -d"
echo ""
echo -e "${RED}SECURITY REMINDER:${NC}"
echo "- Never commit .env to git"
echo "- Keep a secure backup of these credentials"
echo "- Rotate passwords periodically"
